env:
  global:
      - REPO_DIR=statsmodels
      - BUILD_COMMIT=master
      - PLAT=aarch64
      - UNICODE_WIDTH=32
      - NP_BUILD_DEP="numpy==1.19.2"
      - NP_TEST_DEP="numpy==1.19.2"
      - SP_BUILD_DEP="scipy==1.5.3"
      - SP_TEST_DEP="scipy==1.5.3"
      - PANDAS_DEP="pandas==1.1.3"
      - MB_ML_VER=2014
      - DOCKER_TEST_IMAGE=multibuild/xenial_arm64v8
      - ANACONDA_USERNAME=statsmodels
      - OPENBLAS_NUM_THREADS=1
      - OMP_NUM_THREADS=1
      - VML_NUM_THREADS=1
      - MKL_NUM_THREADS=1
      - DAILY_COMMIT=master
      - PYTHONHASHSEED=0

language: python
python: 3.6
sudo: required
arch: arm64-graviton2
dist: focal
virt: vm
group: edge
services: docker

matrix:
  include:
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.7
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.8
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.9

before_install:
    - if [ "$TRAVIS_BRANCH" == "master" ]; then
          CONTAINER="pre-release";
          BUILD_COMMIT=${DAILY_COMMIT:-$BUILD_COMMIT};
      else
          CONTAINER=wheels;
          UPLOAD_ARGS="--no-update-index";
      fi
    - BUILD_DEPENDS="$NP_BUILD_DEP $SP_BUILD_DEP Cython"
    - TEST_DEPENDS="$NP_TEST_DEP $SP_TEST_DEP $PANDAS_DEP nose pytest pytest-xdist pytest-randomly"
    - source multibuild/common_utils.sh
    - source multibuild/travis_steps.sh
    - before_install

install:
    # Maybe get and clean and patch source
    - clean_code $REPO_DIR $BUILD_COMMIT
    - build_wheel $REPO_DIR $PLAT

script:
    - install_run $PLAT

after_success:
    # Upload wheels to anaconda.org
    - source ./anaconda.org/upload-anaconda.sh
