name: Build CI wheels

on:
  push:
    branches: [test-gha]
  pull_request:
    branches: [master]
  schedule:
    - cron: '0 0 * * 0,3'

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        cibw_python: ['cp37-*', 'cp38-*', 'cp39-*']

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64

      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel

      - name: Install VirtualEnv
        run: |
          python -m pip install --upgrade pip
          pip install virtualenv

      - name: Build wheels for CPython
        working-directory: ./statsmodels
        run: |
          python -m cibuildwheel --output-dir dist
        env:
          CIBW_BUILD: ${{ matrix.cibw_python }}
          CIBW_BEFORE_BUILD: pip install numpy==1.19.4 scipy==1.5.3 pandas==1.1.5
          CIBW_TEST_REQUIRES: numpy==1.19.4 scipy==1.5.3 pandas==1.1.5 nose pytest pytest-xdist!=1.30.0 pytest-randomly
          CIBW_ARCHS_LINUX: aarch64

      - uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: ./dist/*.whl
